### ISSUE TITLE
Expose marketing name

### ISSUE THREAD

**Issue by cromefire** [PTFOPlayer/rocm_lib#2]
Right now the library only exposes the chip id as a name (in my case for example `0x744c`), while for me it would be far more interesting to have the markieting name, wich you could actually display to a user (I want to use the library only to display hardware that's being detected by ROCm, the actual usage of ROCm is by a C library I build against).

Output from `rocminfo`:
```
*******                  
Agent 2                  
*******                  
  Name:                    gfx1100                                       
  Marketing Name:          Radeon RX 7900 XTX                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      6144(0x1800) KB                    
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29772(0x744c)
```

Any way that's possible to add to the `Identifiers` struct?

**Comment by PTFOPlayer** [comment]
Feel free to make PR, i will make lookup tables for some more popular models in future but currently i can output only data that i can get from rocm_smi for C.

**Comment by cromefire** [comment]
As the `rocm-smi` CLI already has that info, I'd think it's available via C, right? (no lookup table needed) I do not know the API at all tough.

**Comment by cromefire** [comment]
Okay found the API in `libdrm_amdgpu` (which is kinda part of ROCm as well). Is that still in scope for the project?

**Comment by PTFOPlayer** [comment]
okey thanks i will look into that
